AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Sovereign Kings Backend

Parameters:
  AppName:
    Type: String
    Default: sovereign-kings
  Stage:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod

Resources:
  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AppName}-${Stage}-main-table"
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      DeletionProtectionEnabled: true
    DeletionPolicy: Delete

  AwsLambdaPowertoolsPythonLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: "arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer-extras"
        SemanticVersion: "1.31.1"

  OrderService:
    Type: AWS::Serverless::Application
    Properties:
      Location: Microservices/Order/template.yml
      Parameters:
        AppName: !Ref AppName
        Stage: !Ref Stage
        ServiceName: "order"
        Table: !Ref MainTable
        AwsLambdaPowertoolsPythonLayer: !GetAtt AwsLambdaPowertoolsPythonLayer.Outputs.LayerVersionArn

  ProductService:
    Type: AWS::Serverless::Application
    Properties:
      Location: Microservices/Product/template.yml
      Parameters:
        AppName: !Ref AppName
        Stage: !Ref Stage
        ServiceName: "product"
        Table: !Ref MainTable
        AwsLambdaPowertoolsPythonLayer: !GetAtt AwsLambdaPowertoolsPythonLayer.Outputs.LayerVersionArn